source "http://rubygems.org"

gem 'sinatra'
gem 'rack-recaptcha', :require => 'rack/recaptcha'
gem 'slim'
gem 'data_mapper'
gem 'mhash'

gem 'mysql2'
gem 'dm-mysql-adapter'

# Don't install useless adapters by default
#gem 'mysql2'
#gem 'dm-mysql-adapter'
#gem 'pg'
#gem 'dm-postgres-adapter'
