#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a zomburl
if [[ ! $? -eq 0 ]]; then
exit 1
fi

# Generate random password
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')

# Use 'zomburl' as database name and user
db_user=zomburl

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd
sudo yunohost app setting zomburl mysqlpwd -v $db_pwd


# Copy files to the right place
final_path=/var/www/zomburl
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path


# Change variable in zomburl configuration
sudo cp ../conf/db.rb $final_path/config/db.rb
sudo cp ../conf/Gemfile $final_path/Gemfile
sudo sed -i "s/yunouser/$db_user/g" $final_path/config/db.rb
sudo sed -i "s/yunopass/$db_pwd/g" $final_path/config/db.rb
sudo sed -i "s/yunobase/$db_user/g" $final_path/config/db.rb

# Set permissions
sudo chown -R www-data: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@LOCATIONTOCHANGE@$path@g" ../conf/nginx.conf*
sed -i "s@ALIASTOCHANGE@$final_path@g" ../conf/nginx.conf*
nginxconf=/etc/nginx/conf.d/$domain.d/zomburl.conf
sudo cp ../conf/nginx.conf $nginxconf
sudo chown root: $nginxconf
sudo chmod 600 $nginxconf



# Dependance Zomburl
sudo apt-get install libmysqlclient-dev -y
sudo apt-get install libmhash-dev -y
sudo apt-get install libcurl4-openssl-dev -y
cd $final_path

# Install the PGP key
sudo gpg --keyserver keyserver.ubuntu.com --recv-keys 561F9B9CAC40B2F7
sudo gpg --armor --export 561F9B9CAC40B2F7 | apt-key add -

# Install https support for apt
sudo apt-get install apt-transport-https -y

# Add the passenger apt repository
echo "deb https://oss-binaries.phusionpassenger.com/apt/passenger wheezy main" | sudo tee --append /etc/apt/sources.list.d/passenger.list
sudo chown root: /etc/apt/sources.list.d/passenger.list
sudo chmod 600 /etc/apt/sources.list.d/passenger.list

# Update the apt cache so we can use the new repo
sudo apt-get update

# Install nginx
sudo apt-get install nginx-extras passenger -y

# Set up passenger in the nginx configuration
sudo sed -i "s/#passenger_root/passenger_root/" /etc/nginx/nginx.conf
sed -i "s/#passenger_ruby/passenger_ruby/" /etc/nginx/nginx.conf

# Start nginx
sudo service nginx restart

# Install Zomburl
sudo gem install bundler
bundle install

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app setting zomburl unprotected_uris -v "/"
sudo yunohost app ssowatconf


#sudo yunohost app setting zomburl skipped_uris -d
#sudo yunohost app setting zomburl unprotected_uris -v "/admin"

sudo service nginx reload
sudo yunohost app ssowatconf

