#!/bin/bash

db_user=zomburl
db_name=zomburl
root_pwd=$(sudo cat /etc/yunohost/mysql)
domain=$(sudo yunohost app setting zomburl domain)

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"

sudo rm -rf /var/www/zomburl
sudo rm -f /etc/nginx/conf.d/$domain.d/zomburl.conf